name: collect_ips

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每 3 小时触发，UTC 时间

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 ipwhois pandas

    - name: Run the collect_ips script
      run: |
        echo "Running the collect_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip_info.csv exists and has content
      run: |
        echo "Checking if ip_info.csv exists and has content..."
        if [ -f "ip_info.csv" ]; then
          echo "ip_info.csv exists. Content:"
          cat ip_info.csv
        else:
          echo "ip_info.csv does not exist."
        fi

    - name: Ensure the repository is up to date
      run: |
        echo "Ensuring repository is up-to-date..."
        git pull origin main

    - name: Check if ip_info.csv has changed
      run: |
        echo "Checking if ip_info.csv has changed..."
        git diff --exit-code ip_info.csv || echo "Changes detected in ip_info.csv"

    - name: Commit and push changes if ip_info.csv has changed
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add ip_info.csv if it has changed
        git add ip_info.csv
        
        # Check if there are changes to commit
        if git diff --cached --exit-code; then
          echo "No changes to commit."
        else
          git commit -m "Update ip_info.csv"
          git push origin main
        fi
