name: collect_ips

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每 3 小时触发，UTC 时间

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium ipwhois

    - name: Install Google Chrome
      run: |
        echo "Installing Google Chrome"
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f  # Fix dependencies if needed

    - name: Install compatible ChromeDriver
      run: |
        # 获取当前的 Google Chrome 版本
        GOOGLE_CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
        
        # 获取与 Chrome 版本匹配的 ChromeDriver 版本
        CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${GOOGLE_CHROME_VERSION}")
        
        # 如果获取成功，下载对应版本的 chromedriver
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Error: Unable to fetch ChromeDriver version for Chrome $GOOGLE_CHROME_VERSION"
          exit 1
        fi
        
        echo "Installing ChromeDriver version $CHROMEDRIVER_VERSION"
        
        # 下载并解压缩对应版本的 ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/

    - name: Run the yx_ips script
      run: |
        echo "Running the yx_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip.txt exists and has content
      run: |
        echo "Checking if ip.txt exists and has content..."
        if [ -f "ip.txt" ]; then
          echo "ip.txt exists. Content:"
          cat ip.txt
        else
          echo "ip.txt does not exist."
        fi

    - name: Check if ip.txt has changed
      run: |
        echo "Checking if ip.txt has changed..."
        git status
        git diff ip.txt || echo "No changes detected in ip.txt"

    - name: Commit and push changes
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ip.txt
        git commit -m "Update ip.txt" || echo "No changes to commit"
        git push origin main
