name: collect_ips

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每 3 小时触发，UTC 时间

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 ipwhois selenium

    - name: Get Google Chrome version
      run: |
        GOOGLE_CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        echo "Current Chrome version: $GOOGLE_CHROME_VERSION"
        echo "GOOGLE_CHROME_VERSION=$GOOGLE_CHROME_VERSION" >> $GITHUB_ENV

    - name: Install compatible ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${GOOGLE_CHROME_VERSION})
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        mv chromedriver /usr/local/bin/

    - name: Run the yx_ips script
      run: |
        echo "Running the yx_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip.txt exists and has content
      run: |
        echo "Checking if ip.txt exists and has content..."
        if [ -f "ip.txt" ]; then
          echo "ip.txt exists. Content:"
          cat ip.txt
        else
          echo "ip.txt does not exist."
        fi

    - name: Check if ip.txt has changed
      run: |
        echo "Checking if ip.txt has changed..."
        git status
        git diff ip.txt || echo "No changes detected in ip.txt"

    - name: Commit and push changes
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ip.txt
        git commit -m "Update ip.txt" || echo "No changes to commit"
        git push origin main
