name: collect_ips

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每 3 小时触发，UTC 时间

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 ipwhois pandas  # 添加 pandas

    - name: Run the yx_ips script
      run: |
        echo "Running the yx_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip.txt exists and has content
      run: |
        echo "Checking if ip.txt exists and has content..."
        if [ -f "ip.txt" ]; then
          echo "ip.txt exists. Content:"
          cat ip.txt
        else
          echo "ip.txt does not exist."
        fi

    - name: Ensure the repository is up to date
      run: |
        echo "Ensuring repository is up-to-date..."
        git pull origin main

    - name: Check if ip.txt has changed
      run: |
        echo "Checking if ip.txt has changed..."
        git diff --exit-code ip.txt || echo "Changes detected in ip.txt"

    - name: Commit and push changes if ip.txt has changed
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add ip.txt if it has changed
        git add ip.txt
        
        # Check if there are changes to commit
        if git diff --cached --exit-code; then
          echo "No changes to commit."
        else:
          git commit -m "Update ip.txt"
          git push origin main
