name: collect_ips

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 ipwhois selenium

    - name: Get Chrome version
      id: get_chrome_version
      run: |
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version detected: $CHROME_VERSION"
        # 获取Chrome主版本号
        CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
        echo "Chrome major version: $CHROME_MAJOR_VERSION"
        # 下载对应版本的ChromeDriver
        wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION -O chrome_driver_version
        CHROMEDRIVER_VERSION=$(cat chrome_driver_version)
        echo "ChromeDriver version to download: $CHROMEDRIVER_VERSION"
        wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip -o chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Run the yx_ips script
      run: |
        echo "Running the yx_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip.txt exists and has content
      run: |
        echo "Checking if ip.txt exists and has content..."
        if [ -f "ip.txt" ]; then
          echo "ip.txt exists. Content:"
          cat ip.txt
        else
          echo "ip.txt does not exist."
        fi

    - name: Check if ip.txt has changed
      run: |
        echo "Checking if ip.txt has changed..."
        git status
        git diff ip.txt || echo "No changes detected in ip.txt"

    - name: Commit and push changes
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ip.txt
        git commit -m "Update ip.txt" || echo "No changes to commit"
        git push origin main
