name: collect_ips

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每 3 小时触发，UTC 时间

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests beautifulsoup4 ipwhois pandas

    - name: Install Chrome and ChromeDriver
      run: |
        # 安装 Chrome
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt --fix-broken install -y
        
        # 安装适配 Chrome 版本的 ChromeDriver
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\.[0-9]*$//')  # 获取 Chrome 主版本
        DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        
        # 下载和安装对应版本的 ChromeDriver
        wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        
        google-chrome-stable --version
        chromedriver --version

    - name: Run the collect_ips script
      run: |
        echo "Running the collect_ips script..."
        python collect_ips.py
        echo "collect_ips script completed."

    - name: Check if ip_info.csv and ip.txt exist and have content
      run: |
        echo "Checking if ip_info.csv and ip.txt exist and have content..."
        if [ -f "ip_info.csv" ]; then
          echo "ip_info.csv exists. Content:"
          cat ip_info.csv
        else
          echo "ip_info.csv does not exist."
        fi
        if [ -f "ip.txt" ]; then
          echo "ip.txt exists. Content:"
          cat ip.txt
        else
          echo "ip.txt does not exist."
        fi

    - name: Ensure the repository is up to date
      run: |
        echo "Ensuring repository is up-to-date..."
        git pull origin main

    - name: Check if ip_info.csv or ip.txt have changed
      run: |
        echo "Checking if ip_info.csv or ip.txt have changed..."
        git diff --exit-code ip_info.csv ip.txt || echo "Changes detected"

    - name: Commit and push changes if ip_info.csv or ip.txt have changed
      run: |
        echo "Attempting to commit changes..."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Add ip_info.csv and ip.txt if they have changed
        git add ip_info.csv ip.txt
        
        # Check if there are changes to commit
        if git diff --cached --exit-code; then
          echo "No changes to commit."
        else
          git commit -m "Update ip_info.csv and ip.txt"
          git push origin main
        fi 
