name: Update IP List

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch:  # 手动触发
 # push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3  # 检出代码
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py  # 确保脚本路径正确
    
    - name: Commit and push changes
      run: |
        git config --global user.email "luiquirong@gmail.com"
        git config --global user.name "yd072"
        
        # 查看当前文件更改状态
        if [ -n "$(git status --porcelain)" ]; then
          git add proxyip.txt  # 提交 proxyip.txt 文件
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
