name: Custom IP Speed

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */3 * * *'  # 每3小时自动运行
  push:
    paths:
      - my_ips.txt  # 当 my_ips.txt 更新时触发

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # 保证使用 GITHUB_TOKEN
        fetch-depth: 0  # 保证全量拉取

    - name: Ensure CloudflareST is executable
      run: |
        chmod +x ./CloudflareST  # 确保文件有执行权限

    - name: Run speed test with custom IP list and parameters
      run: |
        ./CloudflareST -f my_ips.txt -url https://download.parallels.com/desktop/v17/17.1.1-51537/ParallelsDesktop-17.1.1-51537.dmg -tl 200 -sl 10 -tp 443 -dn 10 -o result.csv

    - name: Generate best_ips.txt from CSV
      run: |
        cut -d, -f1 result.csv | sed '1d' > best_ips.txt
        cat best_ips.txt

    - name: Commit and push best_ips.txt
      run: |
        # 配置 git 用户信息
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # 使用 GITHUB_TOKEN 认证推送
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # 确保切换到正确的分支
        git checkout main  # 如果你的默认分支是 main，确保执行这个

        # 如果 best_ips.txt 文件有变化，提交并 push
        if ! git diff --quiet best_ips.txt; then
          git add best_ips.txt
          git commit -m "Auto update best_ips.txt from speed test [skip ci]"
          git push
        else
          echo "No changes to best_ips.txt, skip commit."
        fi
